### ISSUE TITLE
Fix world map click function and rendering

### ISSUE THREAD

**Issue by ywwsshDBO** [OpenDBO/OpenDBO-Core#29]
The world map gui should show the second map when clicking the clickable map icon.
![2024-04-24_21-56-22](https://github.com/OpenDBO/OpenDBO-Core/assets/167742178/506f8d49-405d-4b70-b7a1-1198280b81ca)

If character inside the second map world, the world map gui rendering with problem.
![2024-04-24_22-02-11](https://github.com/OpenDBO/OpenDBO-Core/assets/167742178/570d387e-413f-40ac-b821-67d38b65d6e7)

**Comment by drodev** [comment]
this should solve the rendering problem: https://github.com/OpenDBO/OpenDBO-Assets/pull/1

**Comment by ErinnyesDBO** [comment]
This should solve the rendering problem https://github.com/OpenDBO/OpenDBO-Assets/pull/1

**Comment by ywwsshDBO** [comment]
Thank, the rendering problem solved after using the new assets.
