### ISSUE TITLE
CAN'T REPRODUCE: Fix some choppy animations

### ISSUE THREAD

**Issue by GrenderG** [OpenDBO/OpenDBO-Core#41]
As reported by DeadRoseKing:

> it seems to be moving to next part of animation before the first ends causing very choppy visuals its the same with walking flying any transitions of animation

TW Client:

https://github.com/OpenDBO/OpenDBO-Core/assets/8654362/3c977953-7833-4d7c-a8f9-1984813331f1

KR Client:

https://github.com/OpenDBO/OpenDBO-Core/assets/8654362/c3033979-0067-484a-bb31-c1fa36527d35

**Comment by GrenderG** [comment]
UPDATE: I'm not being able to reproduce this issue; animations are playing fine for me. Are any of you able to reproduce it with our current codebase (with no custom changes)?

**Comment by SengokuNadeko** [comment]
I'll try to see if I can reproduce it once I get home

**Comment by AKCore** [comment]
This is a view distance thing. Its not actually a bug but a feature since this game began development in 2008, depending on where it thinks the distance from the camera is, it will play once every 3rd or 4th frame.

**Comment by GrenderG** [comment]
I'm closing this Issue; the only thing to note is the occasional
```
[20:44:57 PM]    CNtlPLObject::SetTriggerAnimation (1551) : [WARNING] pInstanceAnimData == NULL uiAnimKey: 1
```
spam but I don't think that's related to this.
