### ISSUE TITLE
Add missing Armor Properties information

### ISSUE THREAD

**Issue by GrenderG** [OpenDBO/OpenDBO-Core#43]
For some reason Daneos removed the Armor Properties icon and all of its handling, only leaving the Weapon one. It should look like this (screenshot from the TW client):

![imagen](https://github.com/OpenDBO/OpenDBO-Core/assets/8654362/63c81323-ed4e-42b0-91a8-3b253eacfa48)

There is commented out code all over the place; we can use https://github.com/Maufeat/DragonBallOnline/blob/master/DboClient/Client/Gui/InfoWindowGui.cpp (and other related files on this repository) as a reference to bring back all the removed code across all files.

---
> CRASH FIXED IN https://github.com/OpenDBO/OpenDBO-Core/commit/d52db605888c0d16f04c4b2cdd7865d61053a91c

~~Client crashes when hovering the N here:~~
![image](https://github.com/OpenDBO/OpenDBO-Core/assets/8654362/6da4a921-77e5-4024-9f58-e1a96f4574b9)

~~It appears to be caused because the current implementation is half-assed, some original parts were removed most likely by Daneos. All relevant methods need to be reverted back to the originals, we can use this for reference: https://github.com/Maufeat/DragonBallOnline/blob/master/DboClient/Client/Gui/InfoWindowGui.cpp#L3369-L3394~~

~~Also Armor Attributes are missing, they need to be re-enabled in the GUI.~~

**Comment by kingkaibr** [comment]
This isnt a issue or a bug, if you look into the files, he designed the game to work using only one prop by general, instead of using props for weapon and armor, it uses battle props, do you still want to change this? i`m working on it

**Comment by SengokuNadeko** [comment]
Issue fixed with the latest PR! Thanks to @kingkaibr
