### ISSUE TITLE
Game Policies (Contract) dialog not properly working on Login

### ISSUE THREAD

**Issue by GrenderG** [OpenDBO/OpenDBO-Core#6]
The entire Contract version handling seems wrong as only 0 or 1 is being saved to the CONTRACT env variable instead of the actual version. Also, simply checking `GetDboGlobal()->IsAcceptGameContract()` seem to be sometimes returning `false` when it should be `true`, it doesn't always happen though.

We should either remove the storing of contract version and chaning the CONTRACT env variable to be a boolean or fix the entire current handling.

At this moment I removed the code to show the Contract if it hasn't being accepted on login as it was annoying for it to constantly pop up even if you already accepted it.

Related commits:
- https://github.com/OpenDBO/OpenDBO-Core/commit/b478f7016129c1d5795ce925dacf6d4185ab1635
- https://github.com/OpenDBO/OpenDBO-Core/commit/edec02adb6271fed03dd9e8c10456a30e4d7fd5c

**Comment by GrenderG** [comment]
According to @ErinnyesDBO there is a bug in the client, in which the read of properties is not working. So it's very likely that this is causing `IsAcceptGameContract` to sometimes return `false` when it should not.

**Comment by newrom35** [comment]
On pull request : #15

**Comment by GrenderG** [comment]
Thank you!
