### ISSUE TITLE
Error compiling client 

### ISSUE THREAD

**Issue by chusski** [OpenDBO/OpenDBO-Core#70]
Helo and thx for sharing your work.
I am trying to compile the cliente, following guide step by step, but got 2 errors...

![image](https://github.com/user-attachments/assets/cc0020ee-8c71-46ab-bf4a-15039a6a4473)

can someone help ? plz 

thx very much

**Comment by GrenderG** [comment]
Hello! This is not a bug report, please use the support channels on Discord! However, I recommend you closely follow the guide from scratch.

**Comment by chusski** [comment]
oh sorry, can share the discord link, plz
