### ISSUE TITLE
libjpeg version not match? 

### ISSUE THREAD

**Issue by GcloudGameQQ** [OpenDBO/OpenDBO-Core#73]
3rdparty jpeg-6b is not match?  or other else?
![error](https://github.com/user-attachments/assets/d62e0c04-b92e-4fd7-b0f9-829e0c33ead0)
![error2](https://github.com/user-attachments/assets/7d277289-aba3-4eb4-8f30-57e0f930bca4)
it only have msvs80 version,  msvs142 is not exists

**Comment by GcloudGameQQ** [comment]
i use rider and vs2022

**Comment by Lumnaii** [comment]
> 3rdparty jpeg-6b is not match? or other else? ![error](https://private-user-images.githubusercontent.com/143671451/379667357-d62e0c04-b92e-4fd7-b0f9-829e0c33ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTg2MTUsIm5iZiI6MTcyOTkxODMxNSwicGF0aCI6Ii8xNDM2NzE0NTEvMzc5NjY3MzU3LWQ2MmUwYzA0LWI5MmUtNGZkNy1iMGY5LTgyOWUwYzMzZWFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNDUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQwMjM1YzE1YWNhNDE1M2ZmYTQxNDVhMTU5MzJhNDUzYzVhYWIzN2ZkMTQ0ZGFjOGY5YmU0ODBhZmE2YWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FhDxcQFeMI-rCM-M60aSERmqe9PwNozIAR7COf3CnTI) ![error2](https://private-user-images.githubusercontent.com/143671451/379667358-7d277289-aba3-4eb4-8f30-57e0f930bca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTg2MTUsIm5iZiI6MTcyOTkxODMxNSwicGF0aCI6Ii8xNDM2NzE0NTEvMzc5NjY3MzU4LTdkMjc3Mjg5LWFiYTMtNGViNC04ZjMwLTU3ZTBmOTMwYmNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNDUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWM1ODU5MDg0ODVhZDdmOTM5NTliZjFkZDgwN2Y4YzBmZWJmNTQyNzE5NGQyNzQ1ODVkYjVhNDE0ZTJkZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9mOyx4N3PfuHrwB5-JKxDFR01DhkZgb4IzmI1KXv6KU) it only have msvs80 version, msvs142 is not exists

Rename Msvc80 -> Msvc142

**Comment by GcloudGameQQ** [comment]
> > 3rdparty jpeg-6b is not match? or other else? ![error](https://private-user-images.githubusercontent.com/143671451/379667357-d62e0c04-b92e-4fd7-b0f9-829e0c33ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTg2MTUsIm5iZiI6MTcyOTkxODMxNSwicGF0aCI6Ii8xNDM2NzE0NTEvMzc5NjY3MzU3LWQ2MmUwYzA0LWI5MmUtNGZkNy1iMGY5LTgyOWUwYzMzZWFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNDUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQwMjM1YzE1YWNhNDE1M2ZmYTQxNDVhMTU5MzJhNDUzYzVhYWIzN2ZkMTQ0ZGFjOGY5YmU0ODBhZmE2YWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FhDxcQFeMI-rCM-M60aSERmqe9PwNozIAR7COf3CnTI) ![error2](https://private-user-images.githubusercontent.com/143671451/379667358-7d277289-aba3-4eb4-8f30-57e0f930bca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTg2MTUsIm5iZiI6MTcyOTkxODMxNSwicGF0aCI6Ii8xNDM2NzE0NTEvMzc5NjY3MzU4LTdkMjc3Mjg5LWFiYTMtNGViNC04ZjMwLTU3ZTBmOTMwYmNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNDUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWM1ODU5MDg0ODVhZDdmOTM5NTliZjFkZDgwN2Y4YzBmZWJmNTQyNzE5NGQyNzQ1ODVkYjVhNDE0ZTJkZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9mOyx4N3PfuHrwB5-JKxDFR01DhkZgb4IzmI1KXv6KU) it only have msvs80 version, msvs142 is not exists
> 
> Rename Msvc80 -> Msvc142

it not useful. i rename the dir  and config linker dir. not useful

**Comment by GcloudGameQQ** [comment]
> > 3rdparty jpeg-6b is not match? or other else? ![error](https://private-user-images.githubusercontent.com/143671451/379667357-d62e0c04-b92e-4fd7-b0f9-829e0c33ead0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTg2MTUsIm5iZiI6MTcyOTkxODMxNSwicGF0aCI6Ii8xNDM2NzE0NTEvMzc5NjY3MzU3LWQ2MmUwYzA0LWI5MmUtNGZkNy1iMGY5LTgyOWUwYzMzZWFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNDUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQwMjM1YzE1YWNhNDE1M2ZmYTQxNDVhMTU5MzJhNDUzYzVhYWIzN2ZkMTQ0ZGFjOGY5YmU0ODBhZmE2YWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FhDxcQFeMI-rCM-M60aSERmqe9PwNozIAR7COf3CnTI) ![error2](https://private-user-images.githubusercontent.com/143671451/379667358-7d277289-aba3-4eb4-8f30-57e0f930bca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTg2MTUsIm5iZiI6MTcyOTkxODMxNSwicGF0aCI6Ii8xNDM2NzE0NTEvMzc5NjY3MzU4LTdkMjc3Mjg5LWFiYTMtNGViNC04ZjMwLTU3ZTBmOTMwYmNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNDUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWM1ODU5MDg0ODVhZDdmOTM5NTliZjFkZDgwN2Y4YzBmZWJmNTQyNzE5NGQyNzQ1ODVkYjVhNDE0ZTJkZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9mOyx4N3PfuHrwB5-JKxDFR01DhkZgb4IzmI1KXv6KU) it only have msvs80 version, msvs142 is not exists
> 
> Rename Msvc80 -> Msvc142

and it tips me function not found

**Comment by GrenderG** [comment]
Please pay attention to the guide and follow it carefully.
